name: voicecook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  lottie: ^3.3.2
  bloc: ^9.1.0
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.3
  image_picker: ^1.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.5.6
  youtube_player_flutter: ^9.0.0
  equatable: ^2.0.7
  flutter_launcher_icons: ^0.14.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
